### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by hunleyd** [despreston/gh-worktree#2]
Just found this lovely extension, installed it, and tried to check the help:
```
╭─doug@nuc ~  ‹main*›
╰─➤  gh worktree --help
failed to run extension: fork/exec /home/doug/.local/share/gh/extensions/gh-worktree/gh-worktree: exec format error
╭─doug@nuc ~  ‹main*›
╰─➤  file /home/doug/.local/share/gh/extensions/gh-worktree/gh-worktree                          1 ↵
/home/doug/.local/share/gh/extensions/gh-worktree/gh-worktree: Mach-O 64-bit x86_64 executable
╭─doug@nuc ~  ‹main*›
╰─➤  cat /etc/os-release                                                                         1 ↵
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.9"
╭─doug@nuc ~  ‹main*›
╰─➤  eix dev-lang/go                                                                             1 ↵
[I] dev-lang/go
     Available versions:  1.18.7(0/1.18.7)^s 1.18.9(0/1.18.9)^s 1.19.2(0/1.19.2)^s{xpak:2} 1.19.4(0/1.19.4)^s{xpak} **9999(0/9999)*l^s {ABI_MIPS="n64 o32" CPU_FLAGS_X86="sse2"}
     Installed versions:  1.19.4(0/1.19.4)^s{xpak}(12:22:13 AM 12/15/2022)(ABI_MIPS="-n64 -o32" CPU_FLAGS_X86="sse2")
     Homepage:            https://go.dev
     Description:         A concurrent garbage collected and typesafe programming language
╭─doug@nuc ~  ‹main*›
╰─➤  uname -a
Linux nuc 6.0.15-gentoo #1 SMP PREEMPT_DYNAMIC Thu Dec 22 08:16:44 EST 2022 x86_64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz GenuineIntel GNU/Linux
```
not sure why it thinks the Mach-O format is correct for me

**Comment by despreston** [comment]
Thanks for sharing this. I forget exactly how gh-cli looks for binaries in an extension repo, but fwiw I only have a single binary in this repo that I built on my mbp. I can look into cross-compiling a few more binaries and pushing those.

**Comment by hunleyd** [comment]
I would _love_ that as I use worktrees almost exclusively and the default `gh` client support for them is .. lacking.

Happy to test and help you debug. Just lmk what you need.

**Comment by black-desk** [comment]
Seems gh will build the binary while installing, so you don't need to build and commit binary to your git repo at all.
Commit binary make this git repo much bigger than it should be. You need to:

1. remove binary in history using git rebase -i;
2. add binary to .gitignore so you will not add it to git repo again by mistake;
3. make a force push to this repo.

Or you can just clone my fork <https://github.com/black-desk/gh-worktree/tree/remove-binary> then make a force push. I have all above setps done.

**Comment by despreston** [comment]
@black-desk Interesting. Looking at the [docs](https://cli.github.com/manual/gh_extension) it seems like you do need a binary, but maybe those docs are out of date? I took a look at one of the more popular extensions [here](https://github.com/dlvhdr/gh-dash) and they aren't including a binary, so I'll go ahead and remove the binary from this repo. Thanks for the insight.

**Comment by black-desk** [comment]
It turns out that cli will download binary from release. After finish all steps above, you need tag something like `v0.0.1`, then the action will automatically build and release the binary. Have a try.

**Comment by despreston** [comment]
Yeah just noticed how that other extension is doing things 👍 . I created a v1.0.0 release so we should be good to go. Thanks again for the help.
