### ISSUE TITLE
Request for license clarification

### ISSUE THREAD

**Issue by tomeon** [despreston/gh-worktree#6]
First, thanks for this extension -- I can't live without my worktrees, and the lack of support in core `gh` really hurt.

I'd like to package up your extension and possibly open a PR to introduce it into the [`nixpkgs` package collection](https://github.com/NixOS/nixpkgs).  However, I don't see a license specified anywhere in this project.  Would you kindly consider adding one in order to make clear whether it is okay to use or redistribute your code?  Thank you very much!

**Comment by despreston** [comment]
👍 all set
